#!/bin/bash

APP_ROOT=$6
WEB_ROOT=$7

echo "	Relink Application Bundle"
echo "		ln -sf ${APP_ROOT}/releases/${DEPLOYED_APPLICATION_NAME}/${BUILD_NUMBER}_${BUILD_ID}/${DEPLOYED_APPLICATION_NAME}.woa ${APP_ROOT}/"
ln -s ${APP_ROOT}/releases/${DEPLOYED_APPLICATION_NAME}/${BUILD_NUMBER}_${BUILD_ID}/${DEPLOYED_APPLICATION_NAME}.woa ${APP_ROOT}/

echo "	Relink WebServerResources Bundle"
echo "		ln -sf ${WEB_ROOT}/releases/${DEPLOYED_APPLICATION_NAME}/${BUILD_NUMBER}_${BUILD_ID}/${DEPLOYED_APPLICATION_NAME}.woa ${WEB_ROOT}/"
ln -s ${WEB_ROOT}/releases/${DEPLOYED_APPLICATION_NAME}/${BUILD_NUMBER}_${BUILD_ID}/${DEPLOYED_APPLICATION_NAME}.woa ${WEB_ROOT}/
